<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2024.
 */

/** @var \BelVG\ShippingManager\Block\Adminhtml\Order\ShippingInfo $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer

/** @var \BelVG\ShippingManager\ViewModel\ShippingInfo\EditViewModel $shippingInfoVM */
$shippingInfoVM = $block->getDataByKey('shippinginfo_edit_view_model');

/** @var \BelVG\ShippingManager\ViewModel\ShippingInfo\DeliveryTypesProvider $deliveryTypesProvider */
$deliveryTypesProvider = $block->getDataByKey('delivery_types_provider_view_model');

/** @var \BelVG\InstallationElements\ViewModel\ShippingInfo\InstallmentViewModel $deliveryTypesProvider */
$installmentVM = $block->getDataByKey('installment_view_model');

$isClaim = 0;
$isInstallment = false;
if ($installmentVM) {
    $isInstallment = $installmentVM->isInstallmentSet();
}
$shippingInfo = false;
$pallets_sizes = [];
$formName = 'belvg_shippingmanager_shippinginfo_form';
$customerComment = $block->getCustomerOrderComment();
$selectedDeliveryType = null;
if (is_object($shippingInfoVM)) {
    /** @var \BelVG\ShippingManager\Api\Data\ShippingInfoInterface $shippingInfo */
    if ($shippingInfo = $shippingInfoVM->getShippingInfo()) {
        $customerDeliveryComment = $escaper->escapeHtml(
            $shippingInfo->getCommentForDelivery(),
            ['b', 'br', 'strong', 'i', 'u', 'a']
        );

        /** generated/code/BelVG/ShippingManager/Api/Data/ShippingInfoExtension.php */
        $extensionAttributes = $shippingInfo->getExtensionAttributes();
        $selectedDeliveryType = $shippingInfo->getDeliveryType();

        $pallets_sizes = json_decode($shippingInfo->getPalletsSizes());
        $customerComment = $shippingInfo->getCommentForDelivery();
        $isClaim = $shippingInfo->getIsClaim();
    }
}

$deliveryDateRequired = $block->isDeliveryDateRequired() ? '<span style="color: red">*</span>' : '';
?>

<section class="admin__page-section belvg_shipping_info">
    <div class="admin__page-section-title">
        <span class="title">
            <label for="carrier_provider_select"><?= $escaper->escapeHtml(__('Carrier provider')) ?>&nbsp;</label>
        </span>

        <?= $block->getChildHtml('BelVG_ShippingManager.carrier_provider'); ?>

    </div>
    <div class="admin__page-section-content">
        <?= $block->getChildHtml('BelVG_ShippingManager.carrier_provider.form'); ?>

        <table cellspacing="0" class="data-table admin__control-table" attr-carrier_provider="consignor">
            <thead>
            <tr class="headings">
                <th><?= $escaper->escapeHtml(__('Information')) ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <div class="shipping-template">
                        <div>
                            <strong><?= $escaper->escapeHtml(__('Template')) ?></strong>
                        </div>
                        <div>
                            <select name="belvg_shippinginfo[template]"
                                    data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                    id="template"
                                    class="select admin__control-select template">
                                <?php foreach ($block->getAvailableShippingTemplates() as $shipping_template): ?>
                                    <option value="<?= $shipping_template['identifier'] ?>"
                                        <?php if ($block->isTemplateSelected($shipping_template)): ?>
                                            selected
                                        <?php endif; ?>
                                    >
                                        <?= $shipping_template['name'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                </td>
            </tr>

            <tr>
                <td>
                    <div>
                        <strong><?= $escaper->escapeHtml(__('Delivery Information')) ?></strong>
                    </div>
                    <div class="delivery-info">
                        <input class="input-text admin__control-text delivery0"
                               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                               type="text"
                               name="belvg_shippinginfo[delivery0]"
                               id="delivery0"
                               value="<?= $escaper->escapeHtml($block->getLine1()) ?>">
                        <input class="input-text admin__control-text delivery1"
                               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                               type="text"
                               name="belvg_shippinginfo[delivery1]"
                               id="delivery1"
                               value="<?= $escaper->escapeHtml($block->getLine2()) ?>">
                        <input class="input-text admin__control-text delivery2"
                               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                               type="text"
                               name="belvg_shippinginfo[delivery2]"
                               id="delivery2"
                               value="<?= $escaper->escapeHtml($block->getLine3()) ?>">
                        <input class="input-text admin__control-text delivery3"
                               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                               type="text"
                               name="belvg_shippinginfo[delivery3]"
                               id="delivery3"
                               value="<?= $escaper->escapeHtml($block->getLine4()) ?>">
                    </div>
                </td>
            </tr>

            </tbody>
        </table>

        <table cellspacing="0" class="data-table admin__control-table" id="delivery_info_table">
            <thead>
            <tr class="headings">
                <th><?= $escaper->escapeHtml(__('Common info')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php if($shippingInfo): ?>
                <tr>
                    <td>
                        <div class="shipping-shipping_status">
                            <div>
                                <strong><?= $escaper->escapeHtml(__('Shipping status')) ?></strong>
                            </div>
                            <div>
                                <select name="belvg_shippinginfo[shipping_status]"
                                        data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                        id="shipping_status"
                                        class="select admin__control-select shipping_status">
                                    <?php foreach ($shippingInfoVM->getShippingStatuses() as $statuses): ?>
                                        <option
                                            value="<?= $escaper->escapeHtml($statuses['value']) ?>"
                                            <?php if($statuses['value'] == $shippingInfo->getStatus()): ?> selected="selected" <?php endif; ?>
                                        >
                                            <?= $escaper->escapeHtml($statuses['label']) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td>
                    <div class="shipping-is_claim">
                        <div>
                            <strong><?= $escaper->escapeHtml(__('Is claim')) ?></strong>
                        </div>
                        <div>
                            <select name="belvg_shippinginfo[is_claim]"
                                    data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                    id="is_claim"
                                    class="select admin__control-select is_claim">
                                <option value="0" <?php if($isClaim == 0): ?> selected="selected" <?php endif; ?>><?= $escaper->escapeHtml(__('No')) ?></option>
                                <option value="1" <?php if($isClaim == 1): ?> selected="selected" <?php endif; ?>><?= $escaper->escapeHtml(__('Yes')) ?></option>
                            </select>
                        </div>
                    </div>
                    <div class="shipping-delivery_type">
                        <div>
                            <strong><?= $escaper->escapeHtml(__('Delivery type')) ?></strong>
                        </div>

                        <div>
                            <?php
                            $order = $block->getShippingInfoOrder();
                            if($order) {
                                echo $block->getChildBlock("BelVG_ShippingManager.carrier_provider.delivery_type")->setOrder($order)->toHtml();
                            }
                            ?>
                        </div>
                    </div>
                </td>
            </tr>
            <!--            Contains Installment start-->
            <tr id="installation-is-set_container">
                <td>
                    <div class="shipping-contains_installment">
                        <div>
                            <strong><?= $escaper->escapeHtml(__('Contains Installment')) ?></strong>
                        </div>
                        <div id="installation-is-set">
                            <select name="belvg_shippinginfo[installation_is_set]"
                                    data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                    id="installation-is-set_select"
                                    class="select admin__control-select contains_installment">
                                <option value="0"><?= $escaper->escapeHtml(__('No')) ?></option>
                                <option value="1" ><?= $escaper->escapeHtml(__('Yes')) ?></option>
                            </select>
                        </div>
                    </div>
                </td>
            </tr>
            <!--            Contains Installment ent-->
            </tbody>
        </table>

        <table cellspacing="0" class="data-table admin__control-table" id="delivery_info_table">
            <thead>
            <tr class="headings">
                <th><?= $escaper->escapeHtml(__('Pallets Qty')) ?></th>
                <th><?= $escaper->escapeHtml(__('Pallets Sizes')) ?></th>
            </tr>
            </thead>
            <tbody id="delivery-info-table-container">
            <tr id="delivery-info-table-template" class="template">
                <td width="200">
                    <select name="belvg_shippinginfo[pallets_qty]"
                            data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                            id="pallets-qty"
                            class="admin__control-select required-entry">
                        <?php for ($i=1; $i<31; $i++): ?>
                            <option value="<?= $i ?>"
                                    <?php if ($shippingInfo && $shippingInfo->getPalletsQty() == $i): ?>selected<?php endif; ?>>
                                <?= $i ?>
                            </option>
                        <?php endfor; ?>
                    </select>

                    <input name="belvg_shippinginfo[pallets_qty_man]"
                           placeholder="<?= __('Enter pallets quantity manually') ?>"
                           type="text"
                           id="pallets-qty-man"
                           class="input-text admin__control-text " />
                </td>
                <td>
                    <div id="delivery_size_div" class="delivery-size-fields">
                        <!-- todo: rework using dynamicRows component:
                         * https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-dynamicrows.html
                         * https://magento.stackexchange.com/questions/205990/magento2-how-to-add-row-pattern-dynamic-rows-to-the-custom-product-attribute
                         * https://magento.stackexchange.com/questions/165619/how-to-add-magento2-dynamic-rows-deleteaction
                         * https://www.mageknowledge.com/how-to-add-dynamic-rows-in-magento2/
                         -->

                        <?php if ($shippingInfo): ?>
                            <?php for ($j=1; $j<=$shippingInfo->getPalletsQty(); $j++): ?>
                                <div class="cols">
                                    <?php if ($j==1): ?>
                                        <label><?= $escaper->escapeHtml(__('Weight')) ?></label>
                                        <span class="row-heading">(kg)</span>
                                    <?php endif; ?>
                                    <input class="required-entry input-text admin__control-text delivery_size "
                                           data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                           type="text"
                                           name="belvg_shippinginfo[pallets_sizes][<?= $j ?>][Weight]"
                                           value="<?= isset($pallets_sizes->{$j}->Weight) ? $pallets_sizes->{$j}->Weight : '' ?>">
                                </div>
                                <div class="cols">
                                    <?php if ($j==1): ?>
                                        <label><?= $escaper->escapeHtml(__('Length')) ?></label>
                                        <span class="row-heading">(cm)</span>
                                    <?php endif; ?>
                                    <input class="required-entry input-text admin__control-text delivery_size rowlength"
                                           data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                           type="text"
                                           name="belvg_shippinginfo[pallets_sizes][<?= $j ?>][Length]"
                                           value="<?= isset($pallets_sizes->{$j}->Length) ? $pallets_sizes->{$j}->Length : '' ?>">
                                </div>
                                <div class="cols">
                                    <?php if ($j==1): ?><label>
                                        <?= $escaper->escapeHtml(__('Width')) ?></label>
                                        <span class="row-heading">(cm)</span>
                                    <?php endif; ?>
                                    <input class="required-entry input-text admin__control-text delivery_size rowwidth"
                                           data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                           type="text"
                                           name="belvg_shippinginfo[pallets_sizes][<?= $j ?>][Width]"
                                           value="<?= isset($pallets_sizes->{$j}->Width) ? $pallets_sizes->{$j}->Width : '' ?>">
                                </div>
                                <div class="cols">
                                    <?php if ($j==1): ?>
                                        <label><?= $escaper->escapeHtml(__('Height')) ?></label>
                                        <span class="row-heading">(cm)</span>
                                    <?php endif; ?>
                                    <input class="required-entry input-text admin__control-text delivery_size "
                                           data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                           type="text"
                                           name="belvg_shippinginfo[pallets_sizes][<?= $j ?>][Height]"
                                           value="<?= isset($pallets_sizes->{$j}->Height) ? $pallets_sizes->{$j}->Height : '' ?>">
                                </div>
                                <div class="cols">
                                    <?php if ($j==1): ?>
                                        <label><?= $escaper->escapeHtml(__('Loadmeter')) ?></label>
                                        <span class="row-heading">(m)</span>
                                    <?php endif; ?>
                                    <input class="required-entry input-text admin__control-text delivery_size rowloadmeter"
                                           data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                                           type="text"
                                           name="belvg_shippinginfo[pallets_sizes][<?= $j ?>][Loadmeter]"
                                           value="<?= isset($pallets_sizes->{$j}->Loadmeter) ? $pallets_sizes->{$j}->Loadmeter : '' ?>">
                                </div>
                            <?php endfor; ?>
                        <?php else: ?>
                            <div class="cols">
                                <label><?= $escaper->escapeHtml(__('Weight')) ?></label>
                                <span class="row-heading">(kg)</span>
                                <input class="required-entry input-text admin__control-text delivery_size " type="text" name="belvg_shippinginfo[pallets_sizes][1][Weight]" value="">
                            </div>
                            <div class="cols">
                                <label><?= $escaper->escapeHtml(__('Length')) ?></label>
                                <span class="row-heading">(cm)</span>
                                <input class="required-entry input-text admin__control-text delivery_size rowlength" type="text" name="belvg_shippinginfo[pallets_sizes][1][Length]" value="">
                            </div>
                            <div class="cols">
                                <label><?= $escaper->escapeHtml(__('Width')) ?></label>
                                <span class="row-heading">(cm)</span>
                                <input class="required-entry input-text admin__control-text delivery_size rowwidth" type="text" name="belvg_shippinginfo[pallets_sizes][1][Width]" value="">
                            </div>
                            <div class="cols">
                                <label><?= $escaper->escapeHtml(__('Height')) ?></label>
                                <span class="row-heading">(cm)</span>
                                <input class="required-entry input-text admin__control-text delivery_size " type="text" name="belvg_shippinginfo[pallets_sizes][1][Height]" value="">
                            </div>
                            <div class="cols">
                                <label><?= $escaper->escapeHtml(__('Loadmeter')) ?></label>
                                <span class="row-heading">(m)</span>
                                <input class="required-entry input-text admin__control-text delivery_size rowloadmeter" type="text" name="belvg_shippinginfo[pallets_sizes][1][Loadmeter]" value="">
                            </div>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>

            <tr id="delivery_info_table_template" class="template">
                <td width="400">
                    <label for="comment_for_delivery">
                        <strong><?= $escaper->escapeHtml(__('Delivery type')) ?></strong>
                    </label>
                </td>
                <td colspan="2" class="admin__field-control">
                    <?php
                    $order = $block->getShippingInfoOrder();
                    if($order) {
                        echo $block->getChildBlock("BelVG_ShippingManager.carrier_provider.delivery_type")->setOrder($order)->toHtml();
                    }
                    ?>
                </td>
            </tr>
            <tr id="delivery_info_table_template" class="template">
                <td width="400">
                    <label for="comment_for_delivery">
                        <strong><?= $escaper->escapeHtml(__('Shipping comment')) ?></strong>
                    </label>
                </td>
                <td colspan="2" class="admin__field-control">
                    <textarea name="belvg_shippinginfo[comment_for_delivery]" id="comment_for_delivery" class="admin__control-textarea" rows="3" cols="5" data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"><?php if($shippingInfo): ?><?= $escaper->escapeHtml($shippingInfo->getCommentForDelivery()) ?><?php endif; ?></textarea>
                </td>
            </tr>

            <tr id="delivery_info_delivery_date" class="template">
                <td width="400">
                    <strong><?= $escaper->escapeHtml(__('Delivery date')) . $deliveryDateRequired ?></strong>
                </td>
                <td colspan="2" class="admin__field-control">
                    <?=
                    $block->getLayout()->createBlock('BelVG\ShippingManager\Block\View\Element\Date')
                        ->setData([
                            'name' => 'belvg_shippinginfo[delivery_date]',
                            'id' => 'date',
                            'value' => $shippingInfo ? $shippingInfo->getDeliveryDate() : '',
                            'date_format' => 'yyyy-MM-dd',
                            'image' => $this->getViewFileUrl('Magento_Theme::calendar.png'),
                            //                            'years_range' => '-120y:c+nn',
                            'max_date' => '+1y',
                            'min_date' => '0d',
                            'change_month' => 'true',
                            'change_year' => 'true',
                            'show_on' => 'both',
                            'first_day' => 1,
                            'extra_params' => 'data-form-part="' . $formName . '"',
                            'is_required' => $block->isDeliveryDateRequired() ? 'required-entry' : '',
                            'class' => 'delivery-date'
                        ])
                        ->toHtml()
                    ?>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</section>

<div class="installation-js-init"
     data-mage-init='{"BelVG_InstallationElements/js/installation": {
         "valueToInit": "<?= $installmentVM->getInitValue() ?>"
     }
}'></div>

<!--Need it to make works BelVG/InstallationElements/view/adminhtml/ui_component/belvg_shippingmanager_shippinginfo_form.xml:11 -->
<?php $scriptString = <<<script
        require([
            'jquery'
        ], function($) {
            $('.installation-js-init').trigger('contentUpdated');
        })
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<script type="text/javascript">
    var commentsProviders = <?php echo json_encode($customerComment); ?>;
    let customerDeliveryComment = <?= !empty($customerDeliveryComment) ? json_encode($customerDeliveryComment) : '""' ?>;

    require([
        'jquery'
    ], function($) {

        var sizeArray =  new Array( 'Weight','Length','Width','Height','Loadmeter' );

        function addSizesRows(newQty, oldQty) {
            var counter = 0;
            var iArr = 0;

            for (var i=0; i<oldQty; i++) {
                counter++;
            }

            for (var i=1; i<=newQty*sizeArray.length; i++) {
                // counter++;
                if (iArr % sizeArray.length == 0) {
                    var iArr = 0;
                    counter++;
                }

                var arrVal = iArr;

                if (counter == 1) {
                    if(sizeArray[arrVal] == 'Loadmeter'){
                        var label = '<div class="cols"><label>'+sizeArray[arrVal]+'</label><span class="row-heading">(m)</span>';
                    } else {
                        var label = '<div class="cols"><label>'+sizeArray[arrVal]+'</label><span class="row-heading">(cm)</span>';
                    }
                    if(sizeArray[arrVal] == 'Weight'){
                        var label = '<div class="cols"><label>'+sizeArray[arrVal]+'</label><span class="row-heading">(kg)</span>';
                    }
                } else {
                    var label = '<div class="cols">';
                }
                if (sizeArray[arrVal]=='Length') {
                    var rowInputClass = 'rowlength';
                } else if(sizeArray[arrVal]=='Width') {
                    var rowInputClass = 'rowwidth';
                } else if(sizeArray[arrVal]=='Loadmeter') {
                    var rowInputClass = 'rowloadmeter';
                } else {
                    var rowInputClass = '';
                }

                var inputBoxSize = '<input class="required-entry input-text admin__control-text delivery_size '+rowInputClass+'" ' +
                    'type="text" ' +
                    'placeholder-hidden="Row #'+counter+'" ' +
                    'name="belvg_shippinginfo[pallets_sizes]['+counter+']['+sizeArray[arrVal]+']" ' +
                    'data-form-part="<?php echo $formName ?>" ' +
                    'value="" /></div>';
                // var oldContent = $("#delivery_size_div").html();
                $("#delivery_size_div").append(label+' '+inputBoxSize);
                iArr++;
            }
        }

        function removeSizesRows(newQty) {
            var counter = 0;
            var iArr = 0;
            var data = $('#delivery_size_div .cols').get();
            for (var i = data.length - 1; i >= 0; i--) {
                var item = data[i];
                if (iArr % sizeArray.length == 0) {
                    iArr = 0;
                    counter++;
                }

                if (counter > newQty) {
                    return false;
                }

                $(item).remove();
                iArr++;
            }

            // $('#delivery_size_div .cols').get().reverse().each(function(item, nbr){
            //     if (iArr % sizeArray.length == 0) {
            //         iArr = 0;
            //         counter++;
            //     }
            //
            //     if (counter > newQty) {
            //         return false;
            //     }
            //
            //     $(item).remove();
            //     iArr++;
            // });
        }

        function changePalletsQty()
        {
            var palletsQty = Number($("#pallets-qty").val());
            var oldQty = $("#delivery_size_div .cols").length / sizeArray.length;
            var newQty = palletsQty;
            if (newQty > oldQty) {
                var newQty = (newQty - oldQty);
                addSizesRows(newQty, oldQty);
            } else {
                removeSizesRows(oldQty - newQty);
            }
        }

        changePalletsQty();
        $("#pallets-qty").on("change", function(element){
            changePalletsQty();
        });

        $('#delivery_size_div').on('keyup', '.rowwidth', calculateRow);

        function calculateRow() {
            var $row = $(this).closest("div.cols");
            var rowLength = parseFloat($row.prev().find('.rowlength').val());
            var rowWidth = parseFloat($row.find('.rowwidth').val());
            var cost = (rowLength * rowWidth / 2.40) / 10000;

            if (isNaN(cost)) {
                $row.next().next().find('.rowloadmeter').val("0");
            } else {
                // $row.next().next().find('.rowloadmeter').val((cost*100).toFixed(2));
                $row.next().next().find('.rowloadmeter').val((cost).toFixed(2));
            }
        }

        //https://youtrack.belvgdev.com/issue/SD-1483 [end]
        function changeCarrierProvider() {
            var provider = $('#carrier_provider_select').val(),
                commentsProvidersArr = Object.values(commentsProviders),
                comments = '',
                defaultComments = customerDeliveryComment;

            for(var i=0; i<commentsProvidersArr.length; i++) {
                if (commentsProvidersArr[i]['provider'] === provider) {
                    comments = commentsProvidersArr[i]['comments'];
                }
                if (commentsProvidersArr[i]['provider'] === '') {
                    if (comments !== '') {
                        comments += '/n';
                    }

                    comments += commentsProvidersArr[i]['comments'];
                }
            }

            if (comments === '') {
                comments = defaultComments;
            }

            $('#comment_for_delivery').val(comments);
        }
        //run on page load
        changeCarrierProvider();
        $('#carrier_provider_select').on("change", function(element){
            changeCarrierProvider();
        });


        //https://youtrack.belvgdev.com/issue/SD-2053 [Change pallet qty in shipping file]
        function handleManualPalletsQuantityChange() {
            $('#pallets-qty-man').on("change", function(element) {
                var manualQty = $('#pallets-qty-man').val();

                //remove previously added manual items
                $("#pallets-qty")
                    .children("option[isManuallyAdded]")
                    .remove();
                //add new manual items
                $('#pallets-qty').append($('<option>', {
                    value: manualQty,
                    text: manualQty,
                    isManuallyAdded: true
                }));
                //apply manual quantity
                $('#pallets-qty')
                    .val(manualQty)
                    .trigger('change');
            });
        }
        handleManualPalletsQuantityChange()
    });
</script>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        /**
         * https://youtrack.belvgdev.com/issue/SD-1483
         * https://app.asana.com/0/1119668046990941/1200666546804850/f
         *
         * When choosing ”Claim - YES” Delivery type default should be “Delivery”.
         * In almost every claim case we have to deliver it at customer address. But dropdown should still be editable
         */

        let isClaimSelector = '#is_claim';
        function handleIsClaimBehaviorForDeliveryType() {
            let isClaim = Boolean(+$(isClaimSelector).val());

            if (isClaim) {
                $('#delivery_type').val('delivery');
            }
        }
        //run on page load
        handleIsClaimBehaviorForDeliveryType();
        $(isClaimSelector).on("change", function(element){
            handleIsClaimBehaviorForDeliveryType();
        });
    })
</script>
