<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2024.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Checkout\Block\Cart\Item\Renderer $block */

use BelVG\MasterAccount\Api\Service\QuoteItemInterface as MaQuoteItemData;
use BelVG\MasterAccountEmptyOffer\Model\Service\LayoutMaterialForEmptyOffer;

$_item = $block->getItem();
$product = $_item->getProduct();

$product_id = $block->getProduct()->getId();
$product_url = $block->getUrl(
    'checkout/cart/configure',
    [
        'id' => $_item->getId(),
        'product_id' => $product->getId()
    ]
);
if ($_item->getData(MaQuoteItemData::CUSTOM_PRICE) > 0) {
    $product_url = '#'; //Hide link to edit cart for cases when MA price was applied for quote_item
}

/** @var \BelVG\LayoutQuoteItemImg\ViewModel\ImgLocator\MainImageLocator $mainImageLocatorVM */
$mainImageLocatorVM = $block->getData('main_img_locator_view_model');
$mainImage = null;
if (is_object($mainImageLocatorVM)) {
    $mainImage = $mainImageLocatorVM->getMainImage((int)$block->getProduct()->getId());
}

$helper = $this->helper('Magento\Catalog\Helper\Image');
$mainImageData = $mainImage ?
    $mainImage->getData('url') :
    $helper->getDefaultPlaceholderUrl('image');

// For Custom Attrs
$product_id = $product->getId();

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

//BelVG_AdditionalProductAttributes
/** @var \BelVG\AdditionalProductAttributes\ViewModel\SizesConfig $layoutConfigVM */
$layoutConfigVM = $this->getSizeConfigViewModel();
/** @var \BelVG\LayoutCustomizer\Helper\Data $layoutHelper */
$layoutHelper = $layoutConfigVM->getLayoutHelper();
$overall_height = $layoutHelper->getOverallHeightOption();
$overall_width = $layoutHelper->getOverallWidthOption();
$section_sizes = $layoutHelper->getSectionsSizesOption();

/** @var \BelVG\AdditionalProductAttributes\ViewModel\MaterialFinder $materialFinderVM */
$materialFinderVM = $this->getMaterialFinderViewModel();
/** @var \BelVG\LayoutMaterial\Api\Service\GetMaterialByProductInterface $materialFinderService */
$materialFinderService = $materialFinderVM->getMaterialFinderService();
$material = $materialFinderService->getMaterialByProduct($product);
$materialImageConfig = $materialFinderVM->getMaterialImageConfig();
$materialImageService = $materialFinderVM->getMaterialImageService();

/** @var \BelVG\MasterAccountEmptyOffer\ViewModel\EmptyOffer $emptyOfferVM */
$emptyOfferVM = $block->getData('empty_offer_view_model');

$showMembershipPrices = false;
/** @var \BelVG\MembershipDiscount\ViewModel\SubscriptionViewModel $subscriptionViewModel */
$subscriptionViewModel = $block->getSubscriptionViewModel();
if($subscriptionViewModel) {
    $showMembershipPrices = $subscriptionViewModel->isAllowed() || $subscriptionViewModel->showMemberPrices();
//    $isMember = $subscriptionViewModel->isSubscribed();
}

//https://youtrack.belvgdev.com/issue/SD-2104 [Iceland (.is) membership discount]
$membershipDiscountPercent = null;
if ($subscriptionViewModel) {
    $membershipDiscountPercent = $subscriptionViewModel->getDiscountPercent($_item);
}

$_options = $block->getOptionList();
//             BelVG_CustomOrderItemName start
$customName = '';
/** @var \BelVG\CustomOrderItemName\ViewModel\CustomItemName $itemNameViewModel */
if($itemNameViewModel = $block->getData('item_name_view_model')){
    $customName = $itemNameViewModel->getCustomNameByQuoteItem($_item);
    $customName = $customName === '' ? '' : ($customName . '. ');
}
$_options = array_filter($_options, function ($option){
    return !isset($option['option_id']) ? true : $option['option_id'] !== 'belvg_custom_item_name';
});
//            BelVG_CustomOrderItemName end

$sizesString = '';

/** @var \BelVG\SkuDisplay\ViewModel\SkuInDescriptionViewModel $skuInDescriptionViewModel */

$skuInDescriptionViewModel = $block->getSkuInDescriptionViewModel();
$skuInDescription = $skuInDescriptionViewModel ? $skuInDescriptionViewModel->getSku($product) : '';

$productDescName = $customName;
$productDescName .= $block->hasProductUrl() ? $_item->getData('product_second_name') : $block->escapeHtml($_item->getName());

//TODO: rework SIZES
if ($_options) {
    foreach ($_options as $_option) {
        $_formatedOptionValue = $block->getFormatedOptionValue($_option);
        $_mwotOptionValueHash = '';

        if (array_key_exists('mageworx_optiontemplates_group_option_type_id', $_option)) {
            $_mwotOptionValueHash = $_option['mageworx_optiontemplates_group_option_type_id'];
        }
        $is_width = isset($_option['option_id']) ? $layoutHelper->matchDbOptionWithConfig($_option['option_id'], $overall_width, $_mwotOptionValueHash) : false;
        $is_height = isset($_option['option_id']) ? $layoutHelper->matchDbOptionWithConfig($_option['option_id'], $overall_height, $_mwotOptionValueHash) : false;

        if ($is_width || $is_height) {
            if (isset($_formatedOptionValue['full_view'])){
                $sizesString .= $_formatedOptionValue['full_view'];
            } else {
                $sizesString .= $_formatedOptionValue['value'];
            }

            if($is_width) {
                $sizesString .= ' x ';
            }
        }
    }
}
if ($sizesString) {
    $sizesString .= ' ' .__('cm');
}
?>


<li class="cart-item order_<?= $_item['nbr'] ?> installation-product" cart-item-identifier="<?=$_item->getId()?>">
    <div class="belvg-accordion-header">
        <span class="product-desc-name default">
            <span class="product-item-count"><?= $_item['nbr'] ?></span>
            <span>
                <?= $productDescName ?>
                <?php if ($sizesString): ?>
                    <span class="sizes">(<?= $sizesString; ?>)</span>
                <?php endif; ?>
            </span>
        </span>
        <div class="header-actions">
            <?= /* @escapeNotVerified */
            $block->getActions($_item) ?>
        </div>
    </div>
    <div class="product-grid-wrapper">
        <div class="product-photo">
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <button class="open-modal"></button>
            <div class="product-actions actions-toolbar">
                <?= /* @escapeNotVerified */
                $block->getActions($_item) ?>
            </div>
        </div>

        <div class="product-title">
            <h2 class="product-desc-name default">
                <span class="product-item-count"><?= $_item['nbr'] ?></span>
                <span>
                    <?= $productDescName ?>
                    <?php if ($sizesString): ?>
                        <span class="sizes">(<?= $sizesString; ?>)</span>
                    <?php endif; ?>
                </span>
            </h2>

            <p class="subj-cont">
                    <span class="product-name">
                        <?php if (is_object($material)): ?>
                            <span class="product-material"><?= $material->getName(); ?> - </span>
                        <?php elseif($emptyOfferVM): ?>
                            <?= $emptyOfferVM->getLayoutMaterialName($_item->getData(LayoutMaterialForEmptyOffer::LAYOUT_MATERIAL_ID)) ?>
                        <?php endif; ?>
                        <span class="additional">
                            <?php echo $_item->getData('product_additional_description'); ?>
                        </span>

                        <?php if ($skuInDescription): ?>
                            <span class="product-sku">
                                (<?= $skuInDescription; ?>)
                                <meta itemprop="sku" content="<?= $skuInDescription; ?>" />
                            </span>
                        <?php endif; ?>
                    </span>
            </p>
        </div>

        <div class="product-specifications">
                <div class="specification collapsible"
                     data-mage-init='{
                        "collapsible": {
                            "openedState": "active",
                            "saveState": false,
                            "collapsible": true,
                            "animate": { "duration":"300" }
                         }
                     }'>
                    <?php if ($_options): ?>
                        <span class="title" data-role="title">
                        <strong><?php echo __('Specifications') ?></strong>
                    </span>
                        <ul class="item-options" data-role="content" style="display: none">
                            <?php foreach ($_options as $option) : ?>
                                <?php
                                if($option['hidden'] ?? false){
                                    continue;
                                }
                                $formattedLabel = $option['label'];
                                if($option['qty'] ?? false){
                                    $formattedLabel .= ' (' . $option['qty'] . ' ' . __('qty.') . ')';
                                }
                                $formattedLabel .= ': ';
                                ?>
                                <li class="item">
                                    <span class="head"><?= $block->escapeHtml($formattedLabel) ?>
                                    <span class="text">
                                        <?= $block->escapeHtml(
                                            $option['formatted_price']
                                            ?? $option['formatted_value']
                                            ?? $option['value'], ['span']
                                        ) ?>
                                </span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cart item message <?= /* @escapeNotVerified */
                            $message['type'] ?>">
                                <div><?= $block->escapeHtml($message['text']) ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <div class="cart-item-additional-info">
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif; ?>
                </div>
            </div>

        <div class="right-col">
            <div class="product-price price-wrapper">
                <?php //logic was moved to BelVG_LayoutCustomizer::cart/discount_price.phtml ?>
                <?= $this->helper('BelVG\LayoutCustomizer\Helper\DiscountPriceHelper')->formatDiscountPrice($_item) ?>
            </div>

            <div class="product-actions actions-toolbar">
                <?= /* @escapeNotVerified */
                $block->getActions($_item) ?>
            </div>
        </div>

    </div>
</li>


