<?php /** @var BelVG\LayoutCustomizer\Block\Product\View\Customizer $block */ ?>
<?php
$config  = array_merge(
    $block->getCustomizerConfig(),
    [
    'toolbarSelector' => '#belvg-layout-customizer-toolbar'
    ]
);
?>

<aside id="product-customizer" class="product-viewer-2d"></aside>

<script>
    require([ 'jquery',
            'mixins!BelVG_LayoutCustomizer/js/catalog/product/customizer'], function($){
            $('#product-customizer').layoutCustomizer(<?php echo json_encode(array_merge($config, json_decode('{"mainCanvas": true}', true))) ?>)
    })
</script>
