<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2024.
 */

use BelVG\QuotePdf\Block\Order\Item\Renderer\DefaultRenderer;

/** @var  $block DefaultRenderer */

/** @var \Magento\Sales\Model\Order\Item $_item */
$_item = $block->getData('item');
$layoutImg = $block->getData('layoutImg');

$block = $block->getData('block');

$itemName = $_item->getName();
$secondName = $_item->getData('product_second_name');
$additionalDescription = $_item->getData('product_additional_description');

$showMembershipPrices = false;
$subscriptionViewModel = $block->getSubscriptionViewModel();
if($subscriptionViewModel) {
    $showMembershipPrices = $subscriptionViewModel->isAllowed() || $subscriptionViewModel->showMemberPrices();
}
?>
<div class="product-desc">
    <div class="product-desc-name order-item desc order-factory-pdf">
        <div class="count">
            <div class="cont">
                <?= __('Pos') . ' ' . $_item['nbr'] ?>
            </div>
        </div>
    </div>
    <div class="subj-cont">
        <p>
            <span class="subj"><?= $secondName ?></span>
        </p>
        <p><span class="second-name"><?= $additionalDescription ?></span></p>
    </div>

    <div class="product-desc-cont">
        <div class="img-cont">
            <?php if (is_object($layoutImg)): ?>
                <img class="img" src="<?= $layoutImg->getQuoteItemImg() ?>"/>
            <?php endif; ?>
        </div>
        <div class="price-cont <?= $block->getItemsDiscount($_item) != 0 ? 'discount-allowed' : '' ?>">
            <div class="head">
                <?= $showMembershipPrices ? __("Online club price") : __("Your price") ?>
            </div>
            <div class="val">
                <p class="new-price"><?= $block->getItemPriceDiscountInclHtml($_item) ?></p>
            </div>
        </div>
    </div>
</div>

