<?php
/**
 * @package Vinduesgrossisten.
 * @author Simonchik <alexandr.simonchik@gmail.com>
 * @Copyright
 */
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */

$_options = $block->getData('options');
$layoutHelper = $block->getData('layoutHelper');
$overall_width = $block->getData('overall_width');
$overall_height = $block->getData('overall_height');
$section_sizes = $block->getData('section_sizes');
/**
 * default / both_same / both_diff / in_other_white / out_other_white
 * see \BelVG\InsideOutsideColorPrice\Model\OptionPriceCalculator
 */
$colorType = $block->getData('colorType'); // BelVG\InsideOutsideColorPrice\Model\OptionPriceCalculator::getState

$material = $block->getData('material');

/** @var \BelVG\AdditionalProductAttributes\ViewModel\MaterialFinder $materialFinderVM */
$materialFinderVM = $this->getMaterialFinderViewModel();
$materialImageConfig = $materialFinderVM->getMaterialImageConfig();
$materialImageService = $materialFinderVM->getMaterialImageService();

$block = $block->getData('block');
$item = $block->getItem();
$is_factory_pdf_visible = $block->getData('is_factory_pdf_visible');


$mainImageData = '';
$sizesString = '';

/** @var \BelVG\LayoutQuoteItemImg\ViewModel\ImgLocator\MainImageLocator $mainImageLocatorVM */
$mainImageLocatorVM = $block->getData('main_img_locator_view_model');
$mainImage = null;
if (is_object($mainImageLocatorVM) && $item->getProduct()) {
    $mainImage = $mainImageLocatorVM->getMainImage((int)$item->getProduct()->getId());
}

$helper = $this->helper('Magento\Catalog\Helper\Image');
$mainImageData = $mainImage ?
    $mainImage->getData('url') :
    $helper->getDefaultPlaceholderUrl('image');
?>
<?php if ($_options): ?>
    <div class="product-specifications collapsible"
         data-mage-init='{
                    "collapsible": {
                        "openedState": "active",
                        "saveState": false,
                        "collapsible": true,
                        "animate": { "duration":"300" }
                     }
                 }'>
    <span class="title" data-role="title">
        <strong><?= $is_factory_pdf_visible ? 'Specifications' : __('Specifications') ?></strong>
    </span>
        <ul class="item-options" data-role="content" <?= !$is_factory_pdf_visible ? 'style="display: none"' : '' ?>>
            <?php foreach ($_options as $_option) : ?>
                <?php
                $is_hidden = $_option['hidden'] ?? true;
                ?>
                <?php if (!$is_hidden): ?>
                    <li class="item ?>">
                        <span class="head">
                            <?= $block->escapeHtml($_option['label'], ['span', 'b']) ?>:
                        </span>
                        <span class="text">
                                <?= $block->escapeHtml($_option['value'], ['span', 'b']) ?>
                        </span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>

<?php endif; ?>
