<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<div data-role="product-page-loader" class="product-page loading-mask">
    <div class="loader">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
             alt="<?= $escaper->escapeHtml(__('Loading...')); ?>">
    </div>
</div>

<script>
    require(['productPageLoader'], function (productPageLoader) {
        productPageLoader.init('.product-page.loading-mask')
    })
</script>
