<?php
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
/** @var \Magento\Sales\Model\Order\Item $_item */
$_item = $block->getItem();
$_options = $block->getItemOptions();

/** @var \BelVG\AdditionalProductAttributes\ViewModel\MaterialFinder $materialFinderVM */
$materialFinderVM = $this->getMaterialFinderViewModel();
/** @var \BelVG\LayoutMaterial\Api\Service\GetMaterialByProductInterface $materialFinderService */
$materialFinderService = $materialFinderVM->getMaterialFinderService();
$product = $_item->getProduct();
$material = $_item->getMaterial();

$mainImageLocatorVM = $block->getData('main_img_locator_view_model');

//BelVG_AdditionalProductAttributes
/** @var \BelVG\AdditionalProductAttributes\ViewModel\SizesConfig $layoutConfigVM */
$layoutConfigVM = $this->getSizeConfigViewModel();
/** @var \BelVG\LayoutCustomizer\Helper\Data $layoutHelper */
$layoutHelper = $layoutConfigVM->getLayoutHelper();
$overall_height = $layoutHelper->getOverallHeightOption();
$overall_width = $layoutHelper->getOverallWidthOption();
$section_sizes = $layoutHelper->getSectionsSizesOption();

//BelVG_LayoutQuoteItemImg
/** @var \BelVG\LayoutQuoteItemImg\ViewModel\ImgLocator\SalesOrderItem $layoutImgFinderVM */
$layoutImgFinderVM = $this->getSalesOrderItemImgViewModel();
/** @var \BelVG\LayoutQuoteItemImg\Api\Data\QuoteItemImgInterface $layoutImg */
$layoutImg = $layoutImgFinderVM->getObjectForSalesOrderItem($_item->getId());


$descBlock = $block->getChildBlock("installation_product.desc");
$specificationBlock = $block->getChildBlock("installation_product.specification");

$masterKeyLinkedProductsVM = $this->getViewLinkQuoteItems();
$mkLinkedItems = $masterKeyLinkedProductsVM->getLinkedItems($_item);
$masterKeyBlock = $block->getChildBlock("default.masterkey_product_type");

$is_order_factory_pdf = $block->getData('is_order_factory_pdf');
$isOrderHistoryPage = $block->getData('is_order_history_page');

//             BelVG_CustomOrderItemName start
$customName = '';
$itemNameViewModel = $block->getData('item_name_view_model');
/** @var \BelVG\CustomOrderItemName\ViewModel\CustomItemName $itemNameViewModel */
if($itemNameViewModel && empty($mkLinkedItems)){
    $customName = $itemNameViewModel->getCustomNameByOrderItem($_item, $_options, true);
    $customName = $customName === '' ? '' : ($customName . ' ');
}
$sizesString = '';
if ($_options) {
    foreach ($_options as $_option) {
        $_formatedOptionValue = $block->getFormatedOptionValue($_option);
        $is_width = isset($_option['option_id']) ? $layoutHelper->matchDbOptionWithConfig($_option['option_id'], $overall_width) : false;
        $is_height = isset($_option['option_id']) ? $layoutHelper->matchDbOptionWithConfig($_option['option_id'], $overall_height) : false;
        if ($is_width || $is_height) {
            if (isset($_formatedOptionValue['full_view'])){
                $sizesString .= $_formatedOptionValue['full_view'];
            } else {
                $sizesString .= $_formatedOptionValue['value'];
            }

            if($is_width) {
                $sizesString .= ' x ';
            }
        }
    }
}
if ($sizesString) {
    $sizesString .= ' ' .__('cm');
}
?>


<div class="<?= $is_order_factory_pdf ? 'cart-head' : 'product-grid-wrapper' ?> <?= !empty($mkLinkedItems) ? 'master-key-product' : '' ?>">
    <?php if ($descBlock): ?>
        <?php $descBlock->setData([
            'block' => $block,
            'item' => $_item,
            'material' => $material,
            'options' => $_options,
            'layoutHelper' => $layoutHelper,
            'overall_width' => $overall_width,
            'overall_height' => $overall_height,
            'section_sizes' => $section_sizes,
            'layoutImg' => $layoutImg
        ]); ?>
        <?= $this->getChildHtml('installation_product.desc', false) ?>
    <?php endif; ?>

    <?php if (!empty($mkLinkedItems)): ?>
        <?php $masterKeyBlock->setData([
            'linked_items' => $mkLinkedItems,
        ]); ?>
        <?= $this->getChildHtml('default.masterkey_product_type', false) ?>
    <?php elseif ($specificationBlock): ?>
        <?php $colorType = isset($_item->getProductOptions()['info_buyRequest']['color_type']) ? $_item->getProductOptions()['info_buyRequest']['color_type'] : 'default';  //\BelVG\OrderColorType\Observer\OptionsSaveObserver::execute + \BelVG\InsideOutsideColorPrice\Model\OptionPriceCalculator::getState?>
        <?php $specificationBlock->setData([
            'block' => $block,
            'options' => $_options,
            'layoutHelper' => $layoutHelper,
            'overall_width' => $overall_width,
            'overall_height' => $overall_height,
            'section_sizes' => $section_sizes,
            'material' => $material,
            'colorType' => $colorType,
            'material_finder_view_model' => $materialFinderVM,
            'main_img_locator_view_model' => $mainImageLocatorVM
        ]); ?>
        <?= $this->getChildHtml('installation_product.specification', false) ?>
    <?php endif; ?>

    <?= $block->getBlockHtml('default.desc.under.img'); ?>

    <?= $block->getBlockHtml('default.attachments'); ?>

    <div class="item-additional-footer">
        <?= $block->getChildHtml('default.additional.info.footer', false) ?>
    </div>
</div>
