<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2024-2025.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \BelVG\OrderUpgrader\ViewModel\Config $configViewModel */
$configViewModel = $block->getData('config_view_model');

?>
<?php if($configViewModel->isEnabled()): ?>
    <div id="order-upgrader-elements-panel" data-bind="scope:'order-upgrader-elements-panel'" class="order-upgrader-elements-panel">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#order-upgrader-elements-panel": {
                    "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
                }
            }
        </script>
    </div>
<?php endif; ?>
