<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2024.
 */
/** @var $block \BelVG\InstallationElements\Block\Cart\Item\Renderer\Actions\Edit */

?>
<a class="action action-edit"
   id="installation-product-edit-action"
   data-mage-init='{"BelVG_InstallationElements/js/action/edit-installation-product": {} }'
   href=""
   title="<?= $block->escapeHtml(__('Edit item parameters')) ?>">
    <span><?= /* @escapeNotVerified */ __('Edit') ?></span>
</a>
