<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2023-2025.
 */

/** @var $block \BelVG\MeasurementTool\Block\Cart\MeasurementElements */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div id="measurement-elements" data-bind="scope:'measurement-elements'" class="measurement-elements-container">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#measurement-elements": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <?php $serializedConfig = /* @noEscape */ $block->getSerializedMeasurementToolConfig();
    $scriptString = <<<script
        window.measurementToolConfig = {$serializedConfig};
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</div>
