<?php
/*
 * ~ @package Vinduesgrossisten.
 * ~ @author Tsai Eugene <tsai.evgenii@gmail.com>
 * ~ Copyright (c) 2023-2024.
 */

/** @var $block \BelVG\MeasurementTool\Block\View */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div id="measurement_tool" data-bind="scope:'measurement_tool'" class="measurement-tool-container">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#measurement_tool": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <?php $serializedConfig = /* @noEscape */ $block->getSerializedMeasurementToolConfig();
    $scriptString = <<<script
        window.measurementToolConfig = {$serializedConfig};
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</div>
